/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.gui;

import com.org.sistempenjualan.entity.Entity;
import javax.swing.Box;
import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.BarangDao;
import com.org.sistempenjualan.dao.SupplierDao;
import com.org.sistempenjualan.dao.impl.BarangDaoImpl;
import com.org.sistempenjualan.dao.impl.SupplierDaoImpl;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DIOR
 */
public class BarangForm extends javax.swing.JFrame {
     public UserForm userForm;
    
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    BarangDao dao = new BarangDaoImpl();
    SupplierDao sDao = new SupplierDaoImpl();
    
    // Global Variabel
    boolean flagUpdate = false;
    String nikSession = "";
    String kodeSupplier = "";
    
    public BarangForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        nikSession = a.getNikSession();
        userSession.setText("Login As: "+a.getUserSession());
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        mbItem.add(Box.createHorizontalGlue());
        mbItem.add(todayDate);
        mbItem.add(userSession);
        util.tanggalSekarang(todayDate);
        setupTable();
        getListSupplier();
        clearForm();
        generateKodeBarang();
    }
    
    public void setupTable(){
        tblBarang.setModel(DbUtils.resultSetToTableModel(dao.setBarangTable()));
        util.adjustColumn(tblBarang);
    }
    
    public void getListSupplier(){
        cbSupplier.setModel(new DefaultComboBoxModel(sDao.getListSupplier()));
    }
    
    public void clearForm(){
        cbSupplier.setSelectedIndex(0);
        txtNamaBarang.setText("");
        txtCariBarang.setText("");
        txtNamaBarang.setText("");
        txtJmlBarang.setText("0");
        txtHarga.setText("0");
    }
    
    public void generateKodeBarang(){
        try{
            String lastKode = dao.getLastKodeBarang();
            String newKode = "";
            if(!lastKode.equals("")){
                String lastSeq = lastKode.substring(2);
                String newSeqKode = ""+(Integer.parseInt(lastSeq)+1);
                String nol = "";
                if(newSeqKode.length() == 1){
                    nol = "000";
                } else if(newSeqKode.length() == 2){
                    nol = "00";
                } else if(newSeqKode.length() == 3){
                    nol = "0";
                } else if(newSeqKode.length() == 4){
                    nol = "";
                }

                newKode = "PR"+nol+newSeqKode;
            }else{
                newKode = "PR/0001";
            }
            
            txtKodeBarang.setText(newKode);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSupplier = new javax.swing.JLabel();
        lblNamaBarang = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        lblJmlBarang = new javax.swing.JLabel();
        txtJmlBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        lblHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCariBarang = new javax.swing.JTextField();
        lblCariBarang = new javax.swing.JLabel();
        cbSupplier = new javax.swing.JComboBox();
        btnReset = new javax.swing.JButton();
        lblNamaBarang1 = new javax.swing.JLabel();
        txtKodeBarang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mbItem = new javax.swing.JMenuBar();
        btnLogOut = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        todayDate = new javax.swing.JMenu();
        userSession = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Barang");

        lblSupplier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSupplier.setText("Supplier");

        lblNamaBarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNamaBarang.setText("Nama Barang");

        lblJmlBarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJmlBarang.setText("Jumlah Barang");

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        lblHarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblHarga.setText("Harga Barang");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");

        txtCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariBarangKeyReleased(evt);
            }
        });

        lblCariBarang.setText("Cari :");

        cbSupplier.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSupplierActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblNamaBarang1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNamaBarang1.setText("Kode Barang");

        jLabel1.setText("Rp.");

        btnLogOut.setText("Server");

        jMenuItem1.setText("Log Out");
        btnLogOut.add(jMenuItem1);

        mbItem.add(btnLogOut);

        jMenu2.setText("Form");
        mbItem.add(jMenu2);

        todayDate.setText("Date");
        mbItem.add(todayDate);

        userSession.setText("User");
        mbItem.add(userSession);

        setJMenuBar(mbItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCariBarang)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblJmlBarang)
                                .addComponent(txtJmlBarang)
                                .addComponent(lblNamaBarang)
                                .addComponent(txtNamaBarang)
                                .addComponent(lblSupplier)
                                .addComponent(lblHarga)
                                .addComponent(cbSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNamaBarang1)
                            .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCariBarang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSupplier)
                        .addGap(18, 18, 18)
                        .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNamaBarang1)
                        .addGap(18, 18, 18)
                        .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNamaBarang)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblJmlBarang)
                        .addGap(18, 18, 18)
                        .addComponent(txtJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHarga)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)
                            .addComponent(btnReset)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        flagUpdate = false;
        generateKodeBarang();
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        flagUpdate = true;
        int row = tblBarang.getSelectedRow();
        
        TableModel model = tblBarang.getModel();
        
        txtKodeBarang.setText(model.getValueAt(row, 0).toString());
        txtNamaBarang.setText(model.getValueAt(row, 1).toString());
        txtJmlBarang.setText(model.getValueAt(row, 2).toString());
        txtHarga.setText(model.getValueAt(row, 3).toString());
        cbSupplier.setSelectedItem(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblBarangMouseClicked

    private void txtCariBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBarangKeyReleased
        String param = txtCariBarang.getText();
        tblBarang.setModel(DbUtils.resultSetToTableModel(dao.setBarangTable(param)));
        util.adjustColumn(tblBarang);
    }//GEN-LAST:event_txtCariBarangKeyReleased

    private void cbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSupplierActionPerformed
        String supplier = (String) cbSupplier.getSelectedItem();
        String[] arrSupp = supplier.split(" - ");
        kodeSupplier = arrSupp[0];
    }//GEN-LAST:event_cbSupplierActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        boolean result = false;
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JMenu btnLogOut;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCariBarang;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblJmlBarang;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblNamaBarang1;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JMenuBar mbItem;
    private javax.swing.JTable tblBarang;
    private javax.swing.JMenu todayDate;
    private javax.swing.JTextField txtCariBarang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJmlBarang;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JMenu userSession;
    // End of variables declaration//GEN-END:variables
}
