/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.gui;

import com.org.sistempenjualan.entity.Entity;
import javax.swing.Box;
import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.BarangDao;
import com.org.sistempenjualan.dao.impl.BarangDaoImpl;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DIOR
 */
public class BarangForm extends javax.swing.JFrame {
     public UserForm userForm;
    
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    BarangDao dao = new BarangDaoImpl();
    
    // Global Variabel
    boolean flagUpdate = false;
    String nikSession = "";
    
    public BarangForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        nikSession = a.getNikSession();
        userSession.setText("Login As: "+a.getUserSession());
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        mbItem.add(Box.createHorizontalGlue());
        mbItem.add(todayDate);
        mbItem.add(userSession);
        util.tanggalSekarang(todayDate);
        setupTable();
    }
    
    public void setupTable(){
        tblBarang.setModel(DbUtils.resultSetToTableModel(dao.setBarangTable()));
        tblBarang.removeColumn(tblBarang.getColumnModel().getColumn(0));
        util.adjustColumn(tblBarang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSupplier = new javax.swing.JLabel();
        txtSupplier = new javax.swing.JTextField();
        lblNamaBarang = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        lblJmlBarang = new javax.swing.JLabel();
        txtJmlBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        lblHarga = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnCariSupplier = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCariBarang = new javax.swing.JTextField();
        lblCariBarang = new javax.swing.JLabel();
        mbItem = new javax.swing.JMenuBar();
        btnLogOut = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        todayDate = new javax.swing.JMenu();
        userSession = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Barang");

        lblSupplier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSupplier.setText("Supplier");

        lblNamaBarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNamaBarang.setText("Nama Barang");

        lblJmlBarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJmlBarang.setText("Jumlah Barang");

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBarang);

        lblHarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblHarga.setText("Harga Barang");

        btnCariSupplier.setText("Cari");

        btnSimpan.setText("SIMPAN");

        btnHapus.setText("HAPUS");

        lblCariBarang.setText("Cari :");

        btnLogOut.setText("Server");

        jMenuItem1.setText("Log Out");
        btnLogOut.add(jMenuItem1);

        mbItem.add(btnLogOut);

        jMenu2.setText("Form");
        mbItem.add(jMenu2);

        todayDate.setText("Date");
        mbItem.add(todayDate);

        userSession.setText("User");
        mbItem.add(userSession);

        setJMenuBar(mbItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCariBarang)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJmlBarang)
                            .addComponent(txtJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNamaBarang)
                            .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSupplier)
                            .addComponent(lblHarga)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCariSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCariBarang))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSupplier)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariSupplier))
                        .addGap(18, 18, 18)
                        .addComponent(lblNamaBarang)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblJmlBarang)
                        .addGap(18, 18, 18)
                        .addComponent(txtJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHarga)
                        .addGap(18, 18, 18)
                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariSupplier;
    private javax.swing.JButton btnHapus;
    private javax.swing.JMenu btnLogOut;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCariBarang;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblJmlBarang;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JMenuBar mbItem;
    private javax.swing.JTable tblBarang;
    private javax.swing.JMenu todayDate;
    private javax.swing.JTextField txtCariBarang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJmlBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtSupplier;
    private javax.swing.JMenu userSession;
    // End of variables declaration//GEN-END:variables
}
