/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.gui;

import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.BarangDao;
import com.org.sistempenjualan.dao.PemesananDao;
import com.org.sistempenjualan.dao.impl.BarangDaoImpl;
import com.org.sistempenjualan.dao.impl.PemesananDaoImpl;
import com.org.sistempenjualan.entity.Entity;
import java.awt.KeyboardFocusManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author DIOR
 */
public class EditDetailPemesananForm extends javax.swing.JFrame {
    public EditDetailPemesananForm detailForm;
    public SupplierForm supplierForm;
    
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    PemesananDao dao = new PemesananDaoImpl();
    BarangDao brgDao = new BarangDaoImpl();
    
    // Global Variabel
    String nikSession = "";
    int idPemesanan;
    
    public EditDetailPemesananForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        txtKeterangan.setWrapStyleWord(true);
        txtKeterangan.setLineWrap(true);
        txtKeterangan.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, null);
        txtKeterangan.setFocusTraversalKeys(KeyboardFocusManager.BACKWARD_TRAVERSAL_KEYS, null);
        nikSession = a.getNikSession();
        userSession.setText("Login As: "+a.getUserSession());
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        // untuk kebutuhan form ini saja
        idPemesanan = a.getIdPemesanan();
        JOptionPane.showMessageDialog(null,"idPemesanan:"+idPemesanan);
        entity.setIdPemesanan(a.getIdPemesanan());
        entity.setNoPemesanan(a.getNoPemesanan());
        entity.setNoCustomer(a.getNoCustomer());
        txtNoPemesanan.setText(a.getNoPemesanan());
        txtCustomer.setText(a.getNoCustomer());
        mbPemesanan.add(Box.createHorizontalGlue());
        mbPemesanan.add(todayDate);
        mbPemesanan.add(userSession);
        util.tanggalSekarang(todayDate);
        txtNoPemesanan.setEditable(false);
        txtCustomer.setEditable(false);
        setupTable();
        getListBarang();
        clearForm();
    }
    
    public void setupTable(){
        tblPemesanan.setModel(DbUtils.resultSetToTableModel(dao.setDetailPemesananTable(idPemesanan)));
        tblPemesanan.removeColumn(tblPemesanan.getColumnModel().getColumn(0));
        tblPemesanan.removeColumn(tblPemesanan.getColumnModel().getColumn(1));
        tblPemesanan.removeColumn(tblPemesanan.getColumnModel().getColumn(2));
        util.adjustColumn(tblPemesanan);
    }
    
    public void clearForm(){
        cbBarang.setSelectedIndex(0);
        txtJmlBarang.setText("");
        txtKeterangan.setText("");
    }
    
    public void getListBarang(){
        cbBarang.setModel(new DefaultComboBoxModel(brgDao.getListBarang()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoPemesanan = new javax.swing.JLabel();
        txtNoPemesanan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPemesanan = new javax.swing.JTable();
        lblCustomer = new javax.swing.JLabel();
        lblBarang = new javax.swing.JLabel();
        lblJmlBarang = new javax.swing.JLabel();
        txtJmlBarang = new javax.swing.JTextField();
        lblKeterangan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCustomer = new javax.swing.JTextField();
        cbBarang = new javax.swing.JComboBox();
        btnSelesai = new javax.swing.JButton();
        mbPemesanan = new javax.swing.JMenuBar();
        btnLogOut = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        todayDate = new javax.swing.JMenu();
        userSession = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Detail Pemesanan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNoPemesanan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNoPemesanan.setText("No Pemesanan :");

        tblPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPemesanan);

        lblCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCustomer.setText("Customer");

        lblBarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBarang.setText("Barang");

        lblJmlBarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJmlBarang.setText("Jumlah Barang");

        txtJmlBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlBarangActionPerformed(evt);
            }
        });

        lblKeterangan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKeterangan.setText("Keterangan");

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane2.setViewportView(txtKeterangan);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel2.setText("/ Meter");

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        cbBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Barang --" }));

        btnSelesai.setText("SELESAI");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnLogOut.setText("Server");

        jMenuItem2.setText("Log Out");
        btnLogOut.add(jMenuItem2);

        mbPemesanan.add(btnLogOut);

        jMenu2.setText("Form");

        jMenuItem1.setText("Form Surat Jalan");
        jMenu2.add(jMenuItem1);

        mbPemesanan.add(jMenu2);

        todayDate.setText("Date");
        mbPemesanan.add(todayDate);

        userSession.setText("User");
        mbPemesanan.add(userSession);

        setJMenuBar(mbPemesanan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNoPemesanan)
                        .addGap(18, 18, 18)
                        .addComponent(txtNoPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBarang)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtJmlBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJmlBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKeterangan)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoPemesanan)
                    .addComponent(txtNoPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomer)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKeterangan)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBarang)
                        .addGap(18, 18, 18)
                        .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(lblJmlBarang)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSimpan)
                        .addComponent(btnHapus)
                        .addComponent(btnSelesai)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin menutup form?", "Tutup Form", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtJmlBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlBarangActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        int jumlah = 0;
        int stok = 0;
        jumlah = Integer.parseInt(txtJmlBarang.getText());
        String barang = (String) cbBarang.getSelectedItem();
        String[] arrBarang = barang.split(" - ");
        String kodeBarang = arrBarang[0];
        String namaBarang = arrBarang[1];
        String keterangan = txtKeterangan.getText();
        boolean result = false;
        boolean resultUpdateJumlah = false;
        boolean resultUpdateBrg = false;
        try{
            stok = brgDao.getLastStok(namaBarang);
            if(stok - jumlah < 0){
                JOptionPane.showMessageDialog(null,"Stok "+barang+" hanya ada "+stok+", tidak bisa menambah barang!");
            }else{
                entity.setKodeBarang(kodeBarang);
                entity.setJumlahBarang(jumlah);
                entity.setKeteranganPemesanan(keterangan);
                result = dao.createDetailPemesanan(entity);
                if(result){
                    resultUpdateJumlah = dao.tambahJumlahPemesanan(idPemesanan, jumlah);
                    if(resultUpdateJumlah){
                        resultUpdateBrg = brgDao.updateStokBarang(kodeBarang, jumlah);
                        if(resultUpdateBrg){
                            JOptionPane.showMessageDialog(null,"Berhasil tambah barang");
                            setupTable();
                            clearForm();
                        }else{
                            JOptionPane.showMessageDialog(null,"Gagal tambah barang");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Gagal tambah barang");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Gagal tambah barang");
                }
            }
        }catch(Exception e){
            try {
                throw new Exception(e);
            } catch (Exception ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPemesananMouseClicked
        int row = tblPemesanan.getSelectedRow();
        
        TableModel model = tblPemesanan.getModel();
        
        //idCustomer = Integer.parseInt(model.getValueAt(row, 0).toString());
        entity.setIdDetailPemesanan(Integer.parseInt(model.getValueAt(row, 0).toString()));
        entity.setKodeBarang(model.getValueAt(row, 2).toString());
        cbBarang.setSelectedItem(model.getValueAt(row, 5).toString());
        txtJmlBarang.setText(model.getValueAt(row, 6).toString());
        txtKeterangan.setText(model.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tblPemesananMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        boolean resultUpdateJumlah = false;
        boolean result = false;
        boolean resultUpdateBrg = false;
        int jumlah = Integer.parseInt(txtJmlBarang.getText());
        try{
            resultUpdateBrg = brgDao.returnStokBarang(entity.getKodeBarang(), jumlah);
            if(resultUpdateBrg){
                resultUpdateJumlah = dao.kurangJumlahPemesanan(idPemesanan, jumlah);
                if(resultUpdateJumlah){
                    result = dao.deleteDetailPemesanan(entity.getIdDetailPemesanan());
                    if(result){
                        JOptionPane.showMessageDialog(null,"Berhasil hapus barang");
                        setupTable();
                    }else{
                        JOptionPane.showMessageDialog(null,"Gagal hapus barang");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Gagal hapus barang");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Gagal hapus barang");
            }
        }catch(Exception e){
            try {
                throw new Exception(e);
            } catch (Exception ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        
    }//GEN-LAST:event_btnSelesaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JMenu btnLogOut;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cbBarang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBarang;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblJmlBarang;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblNoPemesanan;
    private javax.swing.JMenuBar mbPemesanan;
    private javax.swing.JTable tblPemesanan;
    private javax.swing.JMenu todayDate;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtJmlBarang;
    private javax.swing.JTextArea txtKeterangan;
    private javax.swing.JTextField txtNoPemesanan;
    private javax.swing.JMenu userSession;
    // End of variables declaration//GEN-END:variables
}
