/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.gui;

import com.org.sistempenjualan.backup.DetailSuratJalanForm;
import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.PemesananDao;
import com.org.sistempenjualan.dao.impl.PemesananDaoImpl;
import com.org.sistempenjualan.dao.impl.SuratJalanDaoImpl;
import com.org.sistempenjualan.entity.Entity;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DIOR
 */
public class PemesananForm extends javax.swing.JFrame {
    public DetailSuratJalanForm detialForm;
    public SupplierForm supplierForm;
    
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    PemesananDao dao = new PemesananDaoImpl();
    
    // Global Variabel
    String nikSession = "";
    
    public PemesananForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        nikSession = a.getNikSession();
        userSession.setText("Login As: "+a.getUserSession());
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        setupTable();
        mbPemesanan.add(Box.createHorizontalGlue());
        mbPemesanan.add(todayDate);
        mbPemesanan.add(userSession);
        util.tanggalSekarang(todayDate);
    }
    
    public void setupTable(){
        tblPemesanan.setModel(DbUtils.resultSetToTableModel(dao.setPemesananTable()));
        tblPemesanan.removeColumn(tblPemesanan.getColumnModel().getColumn(0));
        util.adjustColumn(tblPemesanan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPemesanan = new javax.swing.JTable();
        txtCariPemesanan = new javax.swing.JTextField();
        lblCariPemesanan = new javax.swing.JLabel();
        btnSuratBaru = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        mbPemesanan = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLogOut = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuSupplier = new javax.swing.JMenu();
        menuItem = new javax.swing.JMenuItem();
        todayDate = new javax.swing.JMenu();
        userSession = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pemesanan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblPemesanan = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column)
            {
                return false;//This causes all cells to be not editable
            }
        };
        tblPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPemesanan);

        txtCariPemesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPemesananKeyReleased(evt);
            }
        });

        lblCariPemesanan.setText("Cari :");

        btnSuratBaru.setText("Buat Baru");
        btnSuratBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratBaruActionPerformed(evt);
            }
        });

        jButton1.setText("EDIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Server");

        btnLogOut.setText("Log Out");
        jMenu1.add(btnLogOut);

        mbPemesanan.add(jMenu1);

        jMenu2.setText("Form");

        menuSupplier.setText("Form Supplier");
        jMenu2.add(menuSupplier);

        menuItem.setText("Form Item");
        jMenu2.add(menuItem);

        mbPemesanan.add(jMenu2);

        todayDate.setText("Date");
        mbPemesanan.add(todayDate);

        userSession.setText("User");
        mbPemesanan.add(userSession);

        setJMenuBar(mbPemesanan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSuratBaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCariPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCariPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(479, 479, 479)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCariPemesanan)
                    .addComponent(btnSuratBaru))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuratBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratBaruActionPerformed
        this.setVisible(false);
        new PemesananBaruForm(entity).setVisible(true);
    }//GEN-LAST:event_btnSuratBaruActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin menutup form?", "Tutup Form", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtCariPemesananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPemesananKeyReleased
        String param = txtCariPemesanan.getText();
        tblPemesanan.setModel(DbUtils.resultSetToTableModel(dao.setPemesananTable(param)));
        tblPemesanan.removeColumn(tblPemesanan.getColumnModel().getColumn(0));
        util.adjustColumn(tblPemesanan);
    }//GEN-LAST:event_txtCariPemesananKeyReleased

    private void tblPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPemesananMouseClicked
        int row = tblPemesanan.getSelectedRow();
        
        TableModel model = tblPemesanan.getModel();
        
        //idCustomer = Integer.parseInt(model.getValueAt(row, 0).toString());
        entity.setIdPemesanan(Integer.parseInt(model.getValueAt(row, 0).toString()));
        entity.setNoPemesanan(model.getValueAt(row, 1).toString());
        entity.setNoCustomer(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblPemesananMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new EditDetailPemesananForm(entity).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnLogOut;
    private javax.swing.JButton btnSuratBaru;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCariPemesanan;
    private javax.swing.JMenuBar mbPemesanan;
    private javax.swing.JMenuItem menuItem;
    private javax.swing.JMenu menuSupplier;
    private javax.swing.JTable tblPemesanan;
    private javax.swing.JMenu todayDate;
    private javax.swing.JTextField txtCariPemesanan;
    private javax.swing.JMenu userSession;
    // End of variables declaration//GEN-END:variables
}
