/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.gui;

import com.org.sistempenjualan.backup.DetailSuratJalanForm;
import com.org.sistempenjualan.backup.SuratJalanForm;
import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.CustomerDao;
import com.org.sistempenjualan.dao.PemesananDao;
import com.org.sistempenjualan.dao.impl.CustomerDaoImpl;
import com.org.sistempenjualan.dao.impl.PemesananDaoImpl;
import com.org.sistempenjualan.entity.Entity;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DIOR
 */
public class PemesananBaruForm extends javax.swing.JFrame {
    public DetailSuratJalanForm detialForm;
    public SuratJalanForm suratJalanForm;
    
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    PemesananDao dao = new PemesananDaoImpl();
    CustomerDao csDao = new CustomerDaoImpl();
    
    // Global Variabel
    String nikSession = "";
//    public String idPengirim = "";
//    public String namaPengirim = "";
//    public int idCustomer;
//    public String noCustomer = "";
//    public String namaCustomer = "";

    /**
     * Creates new form SuratJalanBaruForm
     */
    public PemesananBaruForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        nikSession = a.getNikSession();
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        generateNoPemesanan();
        txtNoPemesanan.setEditable(false);
        txtTglPemesanan.getCalendar();
        txtTglPemesanan.setMinSelectableDate(new Date());
        getListCustomer();
    }
    
    public void generateNoPemesanan(){
        try{
            Calendar cal = new GregorianCalendar();
            int intBulan = cal.get(Calendar.MONTH);
            String bulan = "";
            if(intBulan<10){
                bulan = "0"+(intBulan+1);
            }else{
                bulan = String.valueOf((intBulan+1));
            }
            int tahun = cal.get(Calendar.YEAR);
            
            String lastKode = dao.getLastNoPemesanan();
            String newKode = "";
            if(!lastKode.equals("")){
                String lastSeq = lastKode.substring(11);
                String newSeqKode = ""+(Integer.parseInt(lastSeq)+1);
                String nol = "";
                if(newSeqKode.length() == 1){
                    nol = "000";
                } else if(newSeqKode.length() == 2){
                    nol = "00";
                } else if(newSeqKode.length() == 3){
                    nol = "0";
                } else if(newSeqKode.length() == 4){
                    nol = "";
                }

                newKode = "PO/"+tahun+"/"+bulan+"/"+nol+newSeqKode;
            }else{
                newKode = "PO/"+tahun+"/"+bulan+"/0001";
            }
            
            txtNoPemesanan.setText(newKode);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }
    
    public void getListCustomer(){
        try{
            cbCustomer.setModel(new DefaultComboBoxModel(csDao.getListCustomer()));
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoPemesanan = new javax.swing.JLabel();
        txtNoPemesanan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        lblTglPemesanan = new javax.swing.JLabel();
        txtTglPemesanan = new com.toedter.calendar.JDateChooser();
        btnCancel = new javax.swing.JButton();
        lblCustomer = new javax.swing.JLabel();
        cbCustomer = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Surat Jalan Baru");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNoPemesanan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNoPemesanan.setText("No Pemesanan");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        lblTglPemesanan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTglPemesanan.setText("Tanggal Pemesanan");

        txtTglPemesanan.setDateFormatString("dd MMMM yyyy");

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCustomer.setText("Customer");

        cbCustomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Pilih Customer --" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNoPemesanan)
                        .addGap(57, 57, 57)
                        .addComponent(txtNoPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTglPemesanan)
                            .addComponent(lblCustomer))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTglPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSimpan)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancel))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoPemesanan)
                    .addComponent(txtNoPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomer)
                    .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTglPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTglPemesanan))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnCancel))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin menutup form?", "Tutup Form", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            this.setVisible(false);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        boolean result = false;
        String noPemesanan = txtNoPemesanan.getText();
        String cbCust = (String) cbCustomer.getSelectedItem();
        String[] arrCb = cbCust.split(" - ");
        String noCustomer = arrCb[0];
        try{
            entity.setNoPemesanan(noPemesanan);
            entity.setTanggalPemesanan(((JTextField)txtTglPemesanan.getDateEditor().getUiComponent()).getText());
            entity.setNoCustomer(noCustomer);
            result = dao.createPemesanan(entity);
            if(result){
                entity.setIdPemesanan(dao.getIdPemesanan(noPemesanan));
                this.setVisible(false);
                new DetailPemesananForm(entity).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Error Membuat Pemesanan Baru!");
            }
        }catch(Exception e){
            try {
                throw new Exception(e);
            } catch (Exception ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
        new PemesananForm(entity).setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cbCustomer;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblNoPemesanan;
    private javax.swing.JLabel lblTglPemesanan;
    private javax.swing.JTextField txtNoPemesanan;
    private com.toedter.calendar.JDateChooser txtTglPemesanan;
    // End of variables declaration//GEN-END:variables
}
