/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.gui;

import com.org.sistempenjualan.DbConnect;
import com.org.sistempenjualan.backup.DetailSuratJalanForm;
import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.PemesananDao;
import com.org.sistempenjualan.dao.impl.PemesananDaoImpl;
import com.org.sistempenjualan.entity.Entity;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DIOR
 */
public class PemesananForm extends javax.swing.JFrame {
    public DetailSuratJalanForm detialForm;
    public SupplierForm supplierForm;
    
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    PemesananDao dao = new PemesananDaoImpl();
    
    // Global Variabel
    String nikSession = "";
    
    public PemesananForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        nikSession = a.getNikSession();
        userSession.setText("Login As: "+a.getUserSession());
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        setupTable();
        mbPemesanan.add(Box.createHorizontalGlue());
        mbPemesanan.add(todayDate);
        mbPemesanan.add(userSession);
        util.tanggalSekarang(todayDate);
        btnEdit.setEnabled(false);
        btnCetakInvoice.setEnabled(false);
    }
    
    public void setupTable(){
        tblPemesanan.setModel(DbUtils.resultSetToTableModel(dao.setPemesananTable()));
        tblPemesanan.removeColumn(tblPemesanan.getColumnModel().getColumn(0));
        util.adjustColumn(tblPemesanan);
    }
    
    public void cetakInvoice(String noPemesanan){
        try {
            String namaFile = "src"+File.separator+"com"+File.separator+"org"+File.separator+"sistempenjualan"+File.separator+"report"+File.separator+"invoice.jasper";
            Connection conn = DbConnect.ConnectDb();

            Map<String,Object> map =  new HashMap<String, Object>();
            map.put("no_pemesanan", noPemesanan);
            JasperPrint jprint = JasperFillManager.fillReport(namaFile.toString(), map, conn);
            if(jprint.getPages().size() != 0){
                JasperViewer.viewReport(jprint,false);
            }else{
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan !");
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPemesanan = new javax.swing.JTable();
        txtCariPemesanan = new javax.swing.JTextField();
        lblCariPemesanan = new javax.swing.JLabel();
        btnSuratBaru = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCetakInvoice = new javax.swing.JButton();
        mbPemesanan = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLogOut = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCustomer = new javax.swing.JMenuItem();
        menuSuratJalan = new javax.swing.JMenuItem();
        todayDate = new javax.swing.JMenu();
        userSession = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pemesanan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblPemesanan = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column)
            {
                return false;//This causes all cells to be not editable
            }
        };
        tblPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPemesanan);

        txtCariPemesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPemesananKeyReleased(evt);
            }
        });

        lblCariPemesanan.setText("Cari :");

        btnSuratBaru.setText("Buat Baru");
        btnSuratBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuratBaruActionPerformed(evt);
            }
        });

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCetakInvoice.setText("CETAK INVOICE");
        btnCetakInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakInvoiceActionPerformed(evt);
            }
        });

        jMenu1.setText("Server");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(btnLogOut);

        mbPemesanan.add(jMenu1);

        jMenu2.setText("Form");

        menuCustomer.setText("Form Customer");
        menuCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCustomerActionPerformed(evt);
            }
        });
        jMenu2.add(menuCustomer);

        menuSuratJalan.setText("Form Surat Jalan");
        menuSuratJalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSuratJalanActionPerformed(evt);
            }
        });
        jMenu2.add(menuSuratJalan);

        mbPemesanan.add(jMenu2);

        todayDate.setText("Date");
        mbPemesanan.add(todayDate);

        userSession.setText("User");
        mbPemesanan.add(userSession);

        setJMenuBar(mbPemesanan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSuratBaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCariPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCariPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnCetakInvoice)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCariPemesanan)
                    .addComponent(btnSuratBaru))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnCetakInvoice))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuratBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuratBaruActionPerformed
        this.setVisible(false);
        new PemesananBaruForm(entity).setVisible(true);
    }//GEN-LAST:event_btnSuratBaruActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin menutup form?", "Tutup Form", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtCariPemesananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPemesananKeyReleased
        String param = txtCariPemesanan.getText();
        tblPemesanan.setModel(DbUtils.resultSetToTableModel(dao.setPemesananTable(param)));
        tblPemesanan.removeColumn(tblPemesanan.getColumnModel().getColumn(0));
        util.adjustColumn(tblPemesanan);
    }//GEN-LAST:event_txtCariPemesananKeyReleased

    private void tblPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPemesananMouseClicked
        btnEdit.setEnabled(true);
        btnCetakInvoice.setEnabled(true);
        int row = tblPemesanan.getSelectedRow();
        
        TableModel model = tblPemesanan.getModel();
        
        //idCustomer = Integer.parseInt(model.getValueAt(row, 0).toString());
        entity.setIdPemesanan(Integer.parseInt(model.getValueAt(row, 0).toString()));
        entity.setNoPemesanan(model.getValueAt(row, 1).toString());
        entity.setNoCustomer(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblPemesananMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        this.setVisible(false);
        new EditDetailPemesananForm(entity).setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void menuCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCustomerActionPerformed
        this.setVisible(false);
        new CustomerForm(entity).setVisible(true);
    }//GEN-LAST:event_menuCustomerActionPerformed

    private void menuSuratJalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSuratJalanActionPerformed
        this.setVisible(false);
        new SuratJalanForm(entity).setVisible(true);
    }//GEN-LAST:event_menuSuratJalanActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCetakInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakInvoiceActionPerformed
        if(entity.getNoPemesanan() != null){
            cetakInvoice(entity.getNoPemesanan());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Silahkan Pilih Nomor Pemesanan");
        }
    }//GEN-LAST:event_btnCetakInvoiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakInvoice;
    private javax.swing.JButton btnEdit;
    private javax.swing.JMenuItem btnLogOut;
    private javax.swing.JButton btnSuratBaru;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCariPemesanan;
    private javax.swing.JMenuBar mbPemesanan;
    private javax.swing.JMenuItem menuCustomer;
    private javax.swing.JMenuItem menuSuratJalan;
    private javax.swing.JTable tblPemesanan;
    private javax.swing.JMenu todayDate;
    private javax.swing.JTextField txtCariPemesanan;
    private javax.swing.JMenu userSession;
    // End of variables declaration//GEN-END:variables
}
