/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.org.sistempenjualan.gui;

import com.org.sistempenjualan.UIUtil;
import com.org.sistempenjualan.dao.BarangDao;
import com.org.sistempenjualan.dao.impl.BarangDaoImpl;
import com.org.sistempenjualan.entity.TransPurchaseDetail;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dialog;
import java.awt.Window;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PurchaseDetailForm extends javax.swing.JPanel {

    public PurchaseDetailForm(Window window) {
        initComponents();
        initDialog(window);        
    }
    
    public static final int ADD = 0;
    public static final int EDIT = 1;
    public static final int VIEW = 2;
    
    private final BarangDao barangDao = new BarangDaoImpl();
    
    private JDialog modelDialog;
    private ActionListener actionListener;
    private TransPurchaseDetail item;
    private int FLAG;

    private void loadItemOption(List<String> exclude) {
        Vector<String> availableOptions = new Vector<>();
        Vector<String> options = barangDao.getListBarang();
        for (String v : options) {
            if (exclude.stream().noneMatch(e -> e.equals(v.split("[-]")[0].trim())))
                availableOptions.add(v);
        }
        cmbBarang.setModel(new DefaultComboBoxModel(availableOptions)); 
        UIUtil.setSelectedIndex(cmbBarang, this.item != null ? String
                .valueOf(this.item.getIdBarang()) : null);
    }
    
    public static interface ActionListener {
        void onUpdated(TransPurchaseDetail item);
        void onAdded(TransPurchaseDetail item);
        void onDeleted(TransPurchaseDetail item);
    }
    
    private void initDialog(Window win) {
        modelDialog = new JDialog(win,Dialog.ModalityType.DOCUMENT_MODAL);
        modelDialog.setTitle(TOOL_TIP_TEXT_KEY);
        Container dialogContainer = modelDialog.getContentPane();
        dialogContainer.setLayout(new BorderLayout());
        
        dialogContainer.add(this, BorderLayout.SOUTH);
        modelDialog.setSize(350, 230);
        modelDialog.setLocationRelativeTo(null);
    }
    
    public void show(TransPurchaseDetail item, int FLAG, ActionListener mActionListener, List<String> excludeCode) {
        this.FLAG = FLAG;
        this.item = this.FLAG == ADD ? new TransPurchaseDetail() : item;
        this.actionListener = mActionListener;
        
        btnDelete.setVisible(FLAG == EDIT);
        cmbBarang.setEnabled(FLAG == ADD);
        txtJumlah.setEditable(FLAG == EDIT || FLAG == ADD);
        btnSubmit.setVisible(FLAG == EDIT || FLAG == ADD);
        btnCancel.setText(FLAG == VIEW ? "TUTUP" : "BATAL");
        
        loadItemOption(excludeCode);
        setItemData();

        modelDialog.setTitle((item == null ? "Add" : "Update") + " Purchase Item");
        modelDialog.setVisible(true);        
    }
    
    private void dismis() {
        modelDialog.setVisible(false);
        clearForm();
    }
    
    private void clearForm() {
        txtJumlah.setText("0");
        UIUtil.setSelectedIndex(cmbBarang, null);
    }
    
    private void setItemData() {
        if (item == null)
            clearForm();
        else {
            UIUtil.setSelectedIndex(cmbBarang, item.getKodeBarang());
            txtJumlah.setText(NumberFormat.getInstance().format(item.getJumlahBarang()));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbBarang = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSubmit.setText("SIMPAN");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel2.setText("Barang");

        txtJumlah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJumlahFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJumlahFocusLost(evt);
            }
        });
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJumlahKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKeyTyped(evt);
            }
        });

        jLabel1.setText("Jumlah");

        btnDelete.setText("HAPUS");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbBarang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnSubmit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(btnCancel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel)
                    .addComponent(btnDelete))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dismis();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            if (cmbBarang.getSelectedIndex() <= 0) {
                JOptionPane.showMessageDialog(null, "Barang belum dipilih !");
                return;
            }
            
            int jumlah = NumberFormat.getInstance().parse(txtJumlah.getText()).intValue();
            if (jumlah == 0) {
                JOptionPane.showMessageDialog(null, "Jumlah barang harus diisi !");
                return;
            }
            
            if (this.FLAG == ADD) {
                String[] barang = cmbBarang.getSelectedItem().toString().split("[-]");
                item.setKodeBarang(barang[0].trim());
                item.setNamaBarang(barang[1].trim());
                item.setJumlahBarang(jumlah);
                actionListener.onAdded(item);
                dismis();
            } else if (this.FLAG == EDIT) {
                item.setJumlahBarang(jumlah);
                actionListener.onUpdated(item);
                dismis();
            }
        } catch (ParseException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Isi jumlah barang dengan angka!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtJumlahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJumlahFocusGained
        UIUtil.deFormatNumber(txtJumlah);
    }//GEN-LAST:event_txtJumlahFocusGained

    private void txtJumlahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJumlahFocusLost
        UIUtil.formatNumber(txtJumlah);
    }//GEN-LAST:event_txtJumlahFocusLost

    private void txtJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyPressed
        
    }//GEN-LAST:event_txtJumlahKeyPressed

    private void txtJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyTyped
        UIUtil.checkOnlyNumber(evt);
    }//GEN-LAST:event_txtJumlahKeyTyped

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        actionListener.onDeleted(item);
        dismis();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
