/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.gui;

import com.org.sistempenjualan.entity.Entity;
import javax.swing.Box;
import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.SupplierDao;
import com.org.sistempenjualan.dao.impl.SupplierDaoImpl;
import java.awt.Dimension;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DIOR
 */
public class SupplierForm extends javax.swing.JFrame {
    public UserForm userForm;
    
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    SupplierDao dao = new SupplierDaoImpl();
    
    // Global Variabel
    boolean flagUpdate = false;
    String nikSession = "";
    
    public SupplierForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        txtAlamat.setWrapStyleWord(true);
        txtAlamat.setLineWrap(true);
        txtAlamat.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, null);
        txtAlamat.setFocusTraversalKeys(KeyboardFocusManager.BACKWARD_TRAVERSAL_KEYS, null);
        setupTable();
        nikSession = a.getNikSession();
        userSession.setText("Login As: "+a.getUserSession());
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        mbSupplier.add(Box.createHorizontalGlue());
        mbSupplier.add(todayDate);
        mbSupplier.add(userSession);
        util.tanggalSekarang(todayDate);
        txtKodeSupplier.setEditable(false);
        btnHapusSupplier.setEnabled(true);
        clearForm();
    }
    
    public void setupTable(){
        tblSupplier.setModel(DbUtils.resultSetToTableModel(dao.setSupplierTable()));
        util.adjustColumn(tblSupplier);
    }
    
    public void clearForm(){
        // Clear Value
        btnSupplierBaru.setText("Baru");
        txtKodeSupplier.setText("");
        txtNamaSupplier.setText("");
        txtAlamat.setText("");
        txtKota.setText("");
        txtNoTlp.setText("");
        setupTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKodeSupplier = new javax.swing.JLabel();
        txtKodeSupplier = new javax.swing.JTextField();
        lblNamaSupplier = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        lblAlamat = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        lblKota = new javax.swing.JLabel();
        lblNoTelp = new javax.swing.JLabel();
        txtNoTlp = new javax.swing.JTextField();
        btnSupplierBaru = new javax.swing.JButton();
        btnSimpanSupplier = new javax.swing.JButton();
        btnHapusSupplier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCariSupplier = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnResetForm = new javax.swing.JButton();
        mbSupplier = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnLogOut = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuUser = new javax.swing.JMenuItem();
        todayDate = new javax.swing.JMenu();
        userSession = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Supplier");
        setPreferredSize(new java.awt.Dimension(1207, 659));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblKodeSupplier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKodeSupplier.setText("Kode Supplier");

        lblNamaSupplier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNamaSupplier.setText("Nama Supplier");

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        lblAlamat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAlamat.setText("Alamat");

        lblKota.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKota.setText("Kota");

        lblNoTelp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNoTelp.setText("No Telepon");

        txtNoTlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNoTlpKeyTyped(evt);
            }
        });

        btnSupplierBaru.setText("Baru");
        btnSupplierBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierBaruActionPerformed(evt);
            }
        });

        btnSimpanSupplier.setText("SIMPAN");
        btnSimpanSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanSupplierActionPerformed(evt);
            }
        });

        btnHapusSupplier.setText("HAPUS");
        btnHapusSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusSupplierActionPerformed(evt);
            }
        });

        jLabel1.setText("Cari :");

        txtCariSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariSupplierKeyReleased(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlamatKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtAlamat);

        btnResetForm.setText("RESET");
        btnResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormActionPerformed(evt);
            }
        });

        jMenu1.setText("Server");

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(btnLogOut);

        mbSupplier.add(jMenu1);

        jMenu2.setText("Form");

        menuUser.setText("Form User");
        menuUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserActionPerformed(evt);
            }
        });
        jMenu2.add(menuUser);

        mbSupplier.add(jMenu2);

        todayDate.setText("Date");
        mbSupplier.add(todayDate);

        userSession.setText("User");
        mbSupplier.add(userSession);

        setJMenuBar(mbSupplier);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(937, 937, 937)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaSupplier)
                            .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKodeSupplier)
                            .addComponent(lblAlamat)
                            .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoTelp)
                            .addComponent(txtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSupplierBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblKota)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpanSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnResetForm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCariSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKodeSupplier)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSupplierBaru))
                        .addGap(18, 18, 18)
                        .addComponent(lblNamaSupplier)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAlamat)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblKota)
                        .addGap(18, 18, 18)
                        .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNoTelp)
                        .addGap(18, 18, 18)
                        .addComponent(txtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapusSupplier)
                            .addComponent(btnResetForm)
                            .addComponent(btnSimpanSupplier)))
                    .addComponent(jScrollPane1))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupplierBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierBaruActionPerformed
        String txtBtnSup = btnSupplierBaru.getText();
        String newKode = "";
        if(txtBtnSup.equals("Baru")){
            flagUpdate = false;
            btnSupplierBaru.setText("Cancel");
            String lastKode = dao.getLastKodeSupplier();
            if(!lastKode.equals("")){
                String lastSeq = lastKode.substring(2);
                String newSeqKode = ""+(Integer.parseInt(lastSeq)+1);
                String nol = "";
                if(newSeqKode.length() == 1){
                    nol = "00";
                } else if(newSeqKode.length() == 2){
                    nol = "0";
                } else if(newSeqKode.length() == 3){
                    nol = "";
                }

                newKode = "SU"+nol+newSeqKode;
            }else{
                newKode = "SU001";
            }
            
            txtKodeSupplier.setText(newKode);
            txtNamaSupplier.setText("");
            txtAlamat.setText("");
            txtKota.setText("");
            txtNoTlp.setText("");
            btnHapusSupplier.setEnabled(false);
        }else{
            flagUpdate = true;
            btnSupplierBaru.setText("Baru");
            txtKodeSupplier.setText("");
            btnHapusSupplier.setEnabled(true);
        }
    }//GEN-LAST:event_btnSupplierBaruActionPerformed

    private void menuUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserActionPerformed
        this.setVisible(false);
        new UserForm(entity).setVisible(true);
    }//GEN-LAST:event_menuUserActionPerformed

    private void btnSimpanSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanSupplierActionPerformed
        boolean result = false;
        int confirm = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menyimpan data?","Simpan Data",JOptionPane.YES_NO_OPTION);
        try{
            if(confirm==0){
                if(!flagUpdate){
                    entity.setKodeSupplier(txtKodeSupplier.getText());
                    entity.setNamaSupplier(txtNamaSupplier.getText());
                    entity.setAlamatSupplier(txtAlamat.getText());
                    entity.setKota(txtKota.getText());
                    entity.setTlpSupplier(txtNoTlp.getText());
                    entity.setNikSession(nikSession);
                    result = dao.addSupplier(entity);
                    if(result){
                        JOptionPane.showMessageDialog(rootPane,"Data Berhasil disimpan!");
                        clearForm();
                    }else{
                        JOptionPane.showMessageDialog(rootPane,"Error Simpan Supplier");
                    }
                }else{
                    entity.setKodeSupplier(txtKodeSupplier.getText());
                    entity.setNamaSupplier(txtNamaSupplier.getText());
                    entity.setAlamatSupplier(txtAlamat.getText());
                    entity.setKota(txtKota.getText());
                    entity.setTlpSupplier(txtNoTlp.getText());
                    entity.setNikSession(nikSession);
                    result = dao.editSupplier(entity);
                    if(result){
                        JOptionPane.showMessageDialog(rootPane,"Data Berhasil diupdate!");
                        clearForm();
                    }else{
                        JOptionPane.showMessageDialog(rootPane,"Error Update Supplier");
                    }
                }
            }
        }catch(Exception e){
            try {
                throw new Exception(e);
            } catch (Exception ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSimpanSupplierActionPerformed

    private void btnResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFormActionPerformed
        clearForm();
    }//GEN-LAST:event_btnResetFormActionPerformed

    private void btnHapusSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusSupplierActionPerformed
        boolean result = false;
        int confirm = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data?","Hapus Data",JOptionPane.YES_NO_OPTION);
        try{
            if(confirm==0){
                result = dao.deleteSupplier(txtKodeSupplier.getText());
                if(result){
                    JOptionPane.showMessageDialog(rootPane,"Data Berhasil dihapus!");
                    clearForm();
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Error Hapus Supplier!");
                }
            }
        }catch(Exception e){
            try {
                throw new Exception(e);
            } catch (Exception ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnHapusSupplierActionPerformed

    private void txtCariSupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariSupplierKeyReleased
        String param = txtCariSupplier.getText();
        tblSupplier.setModel(DbUtils.resultSetToTableModel(dao.getSupplierByParam(param)));
        util.adjustColumn(tblSupplier);
    }//GEN-LAST:event_txtCariSupplierKeyReleased

    private void txtNoTlpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTlpKeyTyped
        if(txtNoTlp.getText().length()>=15){  
           evt.consume();
        }
    }//GEN-LAST:event_txtNoTlpKeyTyped

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        btnSupplierBaru.setText("Baru");
        flagUpdate = true;
        int row = tblSupplier.getSelectedRow();
        
        TableModel model = tblSupplier.getModel();
        
        txtKodeSupplier.setText(model.getValueAt(row, 0).toString());
        txtNamaSupplier.setText(model.getValueAt(row, 1).toString());
        txtAlamat.setText(model.getValueAt(row, 2).toString());
        txtKota.setText(model.getValueAt(row, 3).toString());
        txtNoTlp.setText(model.getValueAt(row, 4).toString());
        btnHapusSupplier.setEnabled(true);
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyPressed
//        if(evt.getKeyCode() == KeyEvent.VK_TAB) {
//            evt.consume();
//        }

    }//GEN-LAST:event_txtAlamatKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin menutup form?", "Tutup Form", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusSupplier;
    private javax.swing.JMenuItem btnLogOut;
    private javax.swing.JButton btnResetForm;
    private javax.swing.JButton btnSimpanSupplier;
    private javax.swing.JButton btnSupplierBaru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblKodeSupplier;
    private javax.swing.JLabel lblKota;
    private javax.swing.JLabel lblNamaSupplier;
    private javax.swing.JLabel lblNoTelp;
    private javax.swing.JMenuBar mbSupplier;
    private javax.swing.JMenuItem menuUser;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JMenu todayDate;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCariSupplier;
    private javax.swing.JTextField txtKodeSupplier;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNamaSupplier;
    private javax.swing.JTextField txtNoTlp;
    private javax.swing.JMenu userSession;
    // End of variables declaration//GEN-END:variables
}
