/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.gui;

import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.PemesananDao;
import com.org.sistempenjualan.dao.SuratJalanDao;
import com.org.sistempenjualan.dao.UserDao;
import com.org.sistempenjualan.dao.impl.PemesananDaoImpl;
import com.org.sistempenjualan.dao.impl.SuratJalanDaoImpl;
import com.org.sistempenjualan.dao.impl.UserDaoImpl;
import com.org.sistempenjualan.entity.Entity;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Box;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DIOR
 */
public class SuratJalanForm extends javax.swing.JFrame {

    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    SuratJalanDao dao = new SuratJalanDaoImpl();
    PemesananDao psnDao = new PemesananDaoImpl();
    UserDao usrDao = new UserDaoImpl();
    
    // Global Variabel
    String nikSession = "";
    int idPemesanan = 0;
    int idSuratJalan = 0;
    
    /**
     * Creates new form SuratJalanForm
     */
    public SuratJalanForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
//        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        nikSession = a.getNikSession();
        userSession.setText("Login As: "+a.getUserSession());
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        mbSuratJalan.add(Box.createHorizontalGlue());
        mbSuratJalan.add(todayDate);
        mbSuratJalan.add(userSession);
        util.tanggalSekarang(todayDate);
        txtNoSuratJalan.setEditable(false);
        setupTable();
        generateNoSuratJalan();
        getListPemesanan();
        getListPengirim();
        clearForm();
    }
    
    public void setupTable(){
        tblSuratJalan.setModel(DbUtils.resultSetToTableModel(dao.setSuratJalanTable()));
        tblSuratJalan.removeColumn(tblSuratJalan.getColumnModel().getColumn(0));
        util.adjustColumn(tblSuratJalan);
    }
    
    public void generateNoSuratJalan(){
        try{
            Calendar cal = new GregorianCalendar();
            int intBulan = cal.get(Calendar.MONTH);
            String bulan = "";
            if(intBulan<10){
                bulan = "0"+(intBulan+1);
            }else{
                bulan = String.valueOf((intBulan+1));
            }
            int tahun = cal.get(Calendar.YEAR);
            
            String lastKode = dao.getLastNoSuratJalan();
            String newKode = "";
            if(!lastKode.equals("")){
                String lastSeq = lastKode.substring(12);
                String newSeqKode = ""+(Integer.parseInt(lastSeq)+1);
                String nol = "";
                if(newSeqKode.length() == 1){
                    nol = "000";
                } else if(newSeqKode.length() == 2){
                    nol = "00";
                } else if(newSeqKode.length() == 3){
                    nol = "0";
                } else if(newSeqKode.length() == 4){
                    nol = "";
                }

                newKode = "SJL/"+tahun+"/"+bulan+"/"+nol+newSeqKode;
            }else{
                newKode = "SJL/"+tahun+"/"+bulan+"/0001";
            }
            
            txtNoSuratJalan.setText(newKode);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }
    
    public void getListPemesanan(){
        cbNoPesanan.setModel(new DefaultComboBoxModel(psnDao.getListNoPemesanan()));
    }
    
    public void getListPengirim(){
        cbPengirim.setModel(new DefaultComboBoxModel(usrDao.getListPengirim()));
    }
    
    public void clearForm(){
        txtCariSuratJalan.setText("");
        cbNoPesanan.setSelectedIndex(0);
        cbPengirim.setSelectedIndex(0);
        ((JTextField)txtTglPengiriman.getDateEditor().getUiComponent()).setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuratJalan = new javax.swing.JTable();
        txtCariSuratJalan = new javax.swing.JTextField();
        lblCariSuratJalan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNoSuratJalan = new javax.swing.JTextField();
        cbNoPesanan = new javax.swing.JComboBox();
        lblNoPesanan = new javax.swing.JLabel();
        lblPengirim = new javax.swing.JLabel();
        cbPengirim = new javax.swing.JComboBox();
        btnSimpan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblTglPengiriman = new javax.swing.JLabel();
        txtTglPengiriman = new com.toedter.calendar.JDateChooser();
        mbSuratJalan = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        todayDate = new javax.swing.JMenu();
        userSession = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Surat Jalan");

        tblSuratJalan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSuratJalan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuratJalanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSuratJalan);

        txtCariSuratJalan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariSuratJalanKeyReleased(evt);
            }
        });

        lblCariSuratJalan.setText("Cari :");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("No Surat Jalan");

        cbNoPesanan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbNoPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNoPesananActionPerformed(evt);
            }
        });

        lblNoPesanan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNoPesanan.setText("No Pemesanan");

        lblPengirim.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPengirim.setText("Pengirim");

        cbPengirim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPengirimActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblTglPengiriman.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTglPengiriman.setText("Tanggal Pengiriman");

        txtTglPengiriman.setDateFormatString("dd MMMM yyyy");

        jMenu1.setText("Server");
        mbSuratJalan.add(jMenu1);

        jMenu2.setText("Form");
        mbSuratJalan.add(jMenu2);

        todayDate.setText("Date");
        mbSuratJalan.add(todayDate);

        userSession.setText("User");
        mbSuratJalan.add(userSession);

        setJMenuBar(mbSuratJalan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNoSuratJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNoPesanan)
                    .addComponent(cbNoPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPengirim)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTglPengiriman)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTglPengiriman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbPengirim, javax.swing.GroupLayout.Alignment.LEADING, 0, 214, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCariSuratJalan)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariSuratJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCariSuratJalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCariSuratJalan))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNoSuratJalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNoPesanan)
                        .addGap(18, 18, 18)
                        .addComponent(cbNoPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPengirim)
                        .addGap(18, 18, 18)
                        .addComponent(cbPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTglPengiriman)
                        .addGap(18, 18, 18)
                        .addComponent(txtTglPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnCancel))))
                .addGap(77, 77, 77))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNoPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNoPesananActionPerformed
        String noPemesanan = (String) cbNoPesanan.getSelectedItem();
        try{
            idPemesanan = psnDao.getIdPemesanan(noPemesanan);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cbNoPesananActionPerformed

    private void cbPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPengirimActionPerformed
        
    }//GEN-LAST:event_cbPengirimActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        boolean result = false;
        String cbVal = (String) cbPengirim.getSelectedItem();
        String noPengiriman = (String) cbNoPesanan.getSelectedItem();
        int idPemesanan;
        String[] arrCb = cbVal.split(" - ");
        String pengirim = arrCb[0];
        String noSuratJalan = txtNoSuratJalan.getText();
        try{
            idPemesanan = psnDao.getIdPemesanan(noPengiriman);
            entity.setNoSuratJalan(noSuratJalan);
            entity.setIdPemesanan(idPemesanan);
            entity.setNikPengirim(pengirim);
            entity.setIdPemesanan(idPemesanan);
            entity.setTanggalPengiriman(((JTextField)txtTglPengiriman.getDateEditor().getUiComponent()).getText());
            result = dao.createSuratJalan(entity);
            if(result){
                JOptionPane.showMessageDialog(null, "Berhasil Simpan Data!");
                generateNoSuratJalan();
                getListPemesanan();
                clearForm();
                setupTable();
            } else {
                JOptionPane.showMessageDialog(null, "Error Simpan Data!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        boolean result = false;
        String noSuratJalan = txtNoSuratJalan.getText();
        
        try{
            if(idSuratJalan == 0){
                idSuratJalan = dao.getIdSuratJalan(noSuratJalan);
            }
            result = dao.cancelSuratJalan(idSuratJalan);
            if(result){
                JOptionPane.showMessageDialog(null, "Berhasil Cancel Data!");
                generateNoSuratJalan();
                getListPemesanan();
                clearForm();
                setupTable();
            } else {
                JOptionPane.showMessageDialog(null, "Error Cancel Data!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCariSuratJalanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariSuratJalanKeyReleased
        String param = txtCariSuratJalan.getText();
        tblSuratJalan.setModel(DbUtils.resultSetToTableModel(dao.setSuratJalanTable(param)));
        tblSuratJalan.removeColumn(tblSuratJalan.getColumnModel().getColumn(0));
        util.adjustColumn(tblSuratJalan);
    }//GEN-LAST:event_txtCariSuratJalanKeyReleased

    private void tblSuratJalanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuratJalanMouseClicked
        int row = tblSuratJalan.getSelectedRow();
        
        TableModel model = tblSuratJalan.getModel();
        
        idSuratJalan = Integer.parseInt(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblSuratJalanMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cbNoPesanan;
    private javax.swing.JComboBox cbPengirim;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCariSuratJalan;
    private javax.swing.JLabel lblNoPesanan;
    private javax.swing.JLabel lblPengirim;
    private javax.swing.JLabel lblTglPengiriman;
    private javax.swing.JMenuBar mbSuratJalan;
    private javax.swing.JTable tblSuratJalan;
    private javax.swing.JMenu todayDate;
    private javax.swing.JTextField txtCariSuratJalan;
    private javax.swing.JTextField txtNoSuratJalan;
    private com.toedter.calendar.JDateChooser txtTglPengiriman;
    private javax.swing.JMenu userSession;
    // End of variables declaration//GEN-END:variables
}
