/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.backup;

import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.CustomerDao;
import com.org.sistempenjualan.dao.impl.CustomerDaoImpl;
import com.org.sistempenjualan.entity.Entity;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DIOR
 */
public class CariCustomerForm extends javax.swing.JFrame {
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    CustomerDao dao = new CustomerDaoImpl();
    
    // Global Variabel
    String nikSession = "";
    
    SuratJalanBaruForm sjlb;
    
    public CariCustomerForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        nikSession = a.getNikSession();
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        setupTable();
        if(a.getNikPengirim() != null){ 
            if(!a.getNikPengirim().equals("")){
                entity.setNikPengirim(a.getNikPengirim());
                entity.setNamaPengirim(a.getNamaPengirim());
            }
        }
    }
    
    public void setupTable(){
        tblCustomer.setModel(DbUtils.resultSetToTableModel(dao.setCustomerTable()));
        tblCustomer.removeColumn(tblCustomer.getColumnModel().getColumn(0));
        util.adjustColumn(tblCustomer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        txtCariCustomer = new javax.swing.JTextField();
        lblCariCustomer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCustomer = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column)
            {
                return false;//This causes all cells to be not editable
            }
        };
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        btnClose.setText("CLOSE");

        txtCariCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariCustomerKeyReleased(evt);
            }
        });

        lblCariCustomer.setText("Cari :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCariCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(329, 329, 329)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCariCustomer))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariCustomerKeyReleased
        String param = txtCariCustomer.getText();
        tblCustomer.setModel(DbUtils.resultSetToTableModel(dao.getCustomerByParam(param)));
        tblCustomer.removeColumn(tblCustomer.getColumnModel().getColumn(0));
        util.adjustColumn(tblCustomer);
    }//GEN-LAST:event_txtCariCustomerKeyReleased

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        if(evt.getClickCount() == 2){
//                JOptionPane.showMessageDialog(null,"Pi");
            int row = tblCustomer.getSelectedRow();

            TableModel model = tblCustomer.getModel();

            int idCustomer = Integer.parseInt(model.getValueAt(row, 0).toString());
            String noCustomer = model.getValueAt(row, 1).toString();
            String namaCustomer = model.getValueAt(row, 2).toString();
            
            entity.setIdCustomer(idCustomer);
            entity.setNoCustomer(noCustomer);
            entity.setNamaCustomer(namaCustomer);

            this.setVisible(false);
            sjlb = new SuratJalanBaruForm(entity);
            sjlb.setVisible(true);
        }
    }//GEN-LAST:event_tblCustomerMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCariCustomer;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtCariCustomer;
    // End of variables declaration//GEN-END:variables
}
