/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.backup;

import com.org.sistempenjualan.gui.*;
import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.UserDao;
import com.org.sistempenjualan.dao.impl.UserDaoImpl;
import com.org.sistempenjualan.entity.Entity;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author DIOR
 */
public class CariPengirimForm extends javax.swing.JFrame {
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    UserDao dao = new UserDaoImpl();
    
    // Global Variabel
    String nikSession = "";
    String nikPengirim = "";
    String namaPengirim = "";
    
    SuratJalanBaruForm sjlb;
    
    public CariPengirimForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        nikSession = a.getNikSession();
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        setupTable();
    }
    
    public void setupTable(){
        tblPengirim.setModel(DbUtils.resultSetToTableModel(dao.setPengirimTable()));
        util.adjustColumn(tblPengirim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPengirim = new javax.swing.JTable();
        txtCariPengirim = new javax.swing.JTextField();
        lblCariPengirim = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Cari Pengirim");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblPengirim = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column)
            {
                return false;//This causes all cells to be not editable
            }
        };
        tblPengirim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPengirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPengirimMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPengirim);

        txtCariPengirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPengirimKeyReleased(evt);
            }
        });

        lblCariPengirim.setText("Cari :");

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCariPengirim)
                                .addGap(18, 18, 18)
                                .addComponent(txtCariPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addGap(359, 359, 359))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCariPengirim))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void tblPengirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPengirimMouseClicked
        if(evt.getClickCount() == 2){
//                JOptionPane.showMessageDialog(null,"Pi");
            int row = tblPengirim.getSelectedRow();

            TableModel model = tblPengirim.getModel();

            nikPengirim = model.getValueAt(row, 0).toString();
            namaPengirim = model.getValueAt(row, 1).toString();
            
            entity.setNikPengirim(nikPengirim);
            entity.setNamaPengirim(namaPengirim);

            this.setVisible(false);
            sjlb = new SuratJalanBaruForm(entity);
            sjlb.setVisible(true);
        }
    }//GEN-LAST:event_tblPengirimMouseClicked

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
        sjlb.setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtCariPengirimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPengirimKeyReleased
        String param = txtCariPengirim.getText();
        tblPengirim.setModel(DbUtils.resultSetToTableModel(dao.setPengirimTableByParam(param)));
        util.adjustColumn(tblPengirim);
    }//GEN-LAST:event_txtCariPengirimKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCariPengirim;
    private javax.swing.JTable tblPengirim;
    private javax.swing.JTextField txtCariPengirim;
    // End of variables declaration//GEN-END:variables
}
