/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.backup;

import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.SuratJalanDao;
import com.org.sistempenjualan.dao.impl.SuratJalanDaoImpl;
import com.org.sistempenjualan.entity.Entity;
import com.org.sistempenjualan.gui.SupplierForm;
import java.awt.KeyboardFocusManager;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author DIOR
 */
public class DetailSuratJalanFormBU extends javax.swing.JFrame {
    public DetailSuratJalanFormBU detailForm;
    public SupplierForm supplierForm;
    
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    SuratJalanDao dao = new SuratJalanDaoImpl();
    
    // Global Variabel
    String nikSession = "";
    int idSuratJalan;
    
    public DetailSuratJalanFormBU(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        txtKeterangan.setWrapStyleWord(true);
        txtKeterangan.setLineWrap(true);
        txtKeterangan.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, null);
        txtKeterangan.setFocusTraversalKeys(KeyboardFocusManager.BACKWARD_TRAVERSAL_KEYS, null);
        setupTable();
        nikSession = a.getNikSession();
        userSession.setText("Login As: "+a.getUserSession());
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        mbSuratJalan.add(Box.createHorizontalGlue());
        mbSuratJalan.add(todayDate);
        mbSuratJalan.add(userSession);
        util.tanggalSekarang(todayDate);
        txtNoSuratJalan.setEditable(false);
        txtPengirim.setEditable(false);
        txtCustomer.setEditable(false);
        txtBarang.setEditable(false);
        clearForm();
        if(a.getIdSuratJalan() != 0){
            entity.setIdSuratJalan(a.getIdSuratJalan());
            entity.setNoSuratJalan(a.getNoSuratJalan());
            txtNoSuratJalan.setText(a.getNoSuratJalan());
        }
        if(a.getNikPengirim() != null && a.getIdCustomer() != 0) {
            entity.setNikPengirim(a.getNikPengirim());
            entity.setNamaPengirim(a.getNamaPengirim());
            entity.setIdCustomer(a.getIdCustomer());
            entity.setNoCustomer(a.getNoCustomer());
            entity.setNamaCustomer(a.getNamaCustomer());
            txtPengirim.setText(entity.getNikPengirim()+" - "+entity.getNamaPengirim());
            txtCustomer.setText(entity.getNoCustomer()+" - "+entity.getNamaCustomer());
        }
        if(a.getIdBarang() != 0){
            txtBarang.setText(entity.getNamaBarang());
        }
        
    }
    
    public void setupTable(){
//        tblSuratJalan.setModel(DbUtils.resultSetToTableModel(dao.setDetailSuratJalanTable(idSuratJalan)));
//        TableModel model = tblSuratJalan.getModel();
//        tblSuratJalan.removeColumn(tblSuratJalan.getColumnModel().getColumn(0));
//        util.adjustColumn(tblSuratJalan);
    }
    
    public void clearForm(){
        txtBarang.setText("");
        txtJmlBarang.setText("");
        txtKeterangan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNoSuratJalan = new javax.swing.JTextField();
        lblPengirim = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuratJalan = new javax.swing.JTable();
        lblCustomer = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JTextField();
        lblBarang = new javax.swing.JLabel();
        txtBarang = new javax.swing.JTextField();
        lblJmlBarang = new javax.swing.JLabel();
        txtJmlBarang = new javax.swing.JTextField();
        btnCariBarang = new javax.swing.JButton();
        lblKeterangan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();
        btnKembali = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        txtPengirim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnKembali1 = new javax.swing.JButton();
        mbSuratJalan = new javax.swing.JMenuBar();
        btnLogOut = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        todayDate = new javax.swing.JMenu();
        userSession = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Detail Surat Jalan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("No Surat Jalan :");

        lblPengirim.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPengirim.setText("Pengirim :");

        tblSuratJalan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSuratJalan);

        lblCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCustomer.setText("Customer");

        lblBarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBarang.setText("Barang");

        txtBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarangActionPerformed(evt);
            }
        });

        lblJmlBarang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJmlBarang.setText("Jumlah Barang");

        txtJmlBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlBarangActionPerformed(evt);
            }
        });

        btnCariBarang.setText("Cari");

        lblKeterangan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKeterangan.setText("Keterangan");

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane2.setViewportView(txtKeterangan);

        btnKembali.setText("KEMBALI");

        btnTambah.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTambah.setText("+");

        jLabel2.setText("/ Meter");

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKembali1.setText("HAPUS");

        btnLogOut.setText("Server");

        jMenuItem2.setText("Log Out");
        btnLogOut.add(jMenuItem2);

        mbSuratJalan.add(btnLogOut);

        jMenu2.setText("Form");

        jMenuItem1.setText("Form Surat Jalan");
        jMenu2.add(jMenuItem1);

        mbSuratJalan.add(jMenu2);

        todayDate.setText("Date");
        mbSuratJalan.add(todayDate);

        userSession.setText("User");
        mbSuratJalan.add(userSession);

        setJMenuBar(mbSuratJalan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNoSuratJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblPengirim)
                        .addGap(18, 18, 18)
                        .addComponent(txtPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lblCustomer)
                        .addGap(18, 18, 18)
                        .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBarang)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtJmlBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJmlBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambah)))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKeterangan)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoSuratJalan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPengirim)
                    .addComponent(txtPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomer)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKeterangan)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBarang)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariBarang))
                        .addGap(18, 18, 18)
                        .addComponent(lblJmlBarang)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambah)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnReset)
                    .addComponent(btnKembali1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin menutup form?", "Tutup Form", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtJmlBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlBarangActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKembali1;
    private javax.swing.JMenu btnLogOut;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBarang;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblJmlBarang;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblPengirim;
    private javax.swing.JMenuBar mbSuratJalan;
    private javax.swing.JTable tblSuratJalan;
    private javax.swing.JMenu todayDate;
    private javax.swing.JTextField txtBarang;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtJmlBarang;
    private javax.swing.JTextArea txtKeterangan;
    private javax.swing.JTextField txtNoSuratJalan;
    private javax.swing.JTextField txtPengirim;
    private javax.swing.JMenu userSession;
    // End of variables declaration//GEN-END:variables
}
