/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.org.sistempenjualan.backup;

import com.org.sistempenjualan.backup.SuratJalanForm;
import com.org.sistempenjualan.backup.CariCustomerForm;
import com.org.sistempenjualan.Utility;
import com.org.sistempenjualan.dao.CustomerDao;
import com.org.sistempenjualan.dao.SuratJalanDao;
import com.org.sistempenjualan.dao.impl.CustomerDaoImpl;
import com.org.sistempenjualan.dao.impl.SuratJalanDaoImpl;
import com.org.sistempenjualan.entity.Entity;
import com.org.sistempenjualan.gui.CariPengirimForm;
import com.org.sistempenjualan.gui.LoginForm;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DIOR
 */
public class SuratJalanBaruForm extends javax.swing.JFrame {
    public DetailSuratJalanForm detialForm;
    public SuratJalanForm suratJalanForm;
    
    // Global Objek
    Entity entity = new Entity();
    Utility util = new Utility();
    SuratJalanDao dao = new SuratJalanDaoImpl();
    
    // Global Variabel
    String nikSession = "";
//    public String idPengirim = "";
//    public String namaPengirim = "";
//    public int idCustomer;
//    public String noCustomer = "";
//    public String namaCustomer = "";

    /**
     * Creates new form SuratJalanBaruForm
     */
    public SuratJalanBaruForm(Entity a) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        nikSession = a.getNikSession();
        entity.setNikSession(nikSession);
        entity.setUserSession(a.getUserSession());
        entity.setRoleSession(a.getRoleSession());
        generateNoSuratJalan();
        txtNoSuratJalanBaru.setEditable(false);
        if(a.getNikPengirim() != null){ 
            if(!a.getNikPengirim().equals("")){
                entity.setNikPengirim(a.getNikPengirim());
                entity.setNamaPengirim(a.getNamaPengirim());
                txtPengirim.setText(entity.getNikPengirim()+" - "+entity.getNamaPengirim());
            }
        }
        if(a.getIdCustomer() != 0){
            entity.setIdCustomer(a.getIdCustomer());
            entity.setNoCustomer(a.getNoCustomer());
            entity.setNamaCustomer(a.getNamaCustomer());
            txtCustomer.setText(entity.getNoCustomer()+" - "+entity.getNamaCustomer());
        }
        txtTglPemesanan.getCalendar();
        txtTglPemesanan.setMinSelectableDate(new Date());
    }
    
    public void generateNoSuratJalan(){
        try{
            Calendar cal = new GregorianCalendar();
            int intBulan = cal.get(Calendar.MONTH);
            String bulan = "";
            if(intBulan<10){
                bulan = "0"+(intBulan+1);
            }else{
                bulan = String.valueOf((intBulan+1));
            }
            int tahun = cal.get(Calendar.YEAR);
            
            String lastKode = dao.getLastNoSuratJalan();
            String newKode = "";
            if(!lastKode.equals("")){
                String lastSeq = lastKode.substring(12);
                String newSeqKode = ""+(Integer.parseInt(lastSeq)+1);
                String nol = "";
                if(newSeqKode.length() == 1){
                    nol = "000";
                } else if(newSeqKode.length() == 2){
                    nol = "00";
                } else if(newSeqKode.length() == 3){
                    nol = "0";
                } else if(newSeqKode.length() == 4){
                    nol = "";
                }

                newKode = "SJL/"+tahun+"/"+bulan+"/"+nol+newSeqKode;
            }else{
                newKode = "SJL/"+tahun+"/"+bulan+"/0001";
            }
            
            txtNoSuratJalanBaru.setText(newKode);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoSuratBaru = new javax.swing.JLabel();
        txtNoSuratJalanBaru = new javax.swing.JTextField();
        lblPengirim = new javax.swing.JLabel();
        txtPengirim = new javax.swing.JTextField();
        btnCariPengirim = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        lblTglPemesanan = new javax.swing.JLabel();
        txtTglPemesanan = new com.toedter.calendar.JDateChooser();
        btnCancel = new javax.swing.JButton();
        lblCustomer = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JTextField();
        btnCariCustomer = new javax.swing.JButton();
        lblTglPemesanan1 = new javax.swing.JLabel();
        txtTglPengiriman = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Surat Jalan Baru");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNoSuratBaru.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNoSuratBaru.setText("No Surat Jalan");

        lblPengirim.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPengirim.setText("Pengirim");

        btnCariPengirim.setText("Cari");
        btnCariPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPengirimActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        lblTglPemesanan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTglPemesanan.setText("Tanggal Pemesanan");

        txtTglPemesanan.setDateFormatString("dd MMMM yyyy");

        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblCustomer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCustomer.setText("Customer");

        txtCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerActionPerformed(evt);
            }
        });

        btnCariCustomer.setText("Cari");
        btnCariCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariCustomerActionPerformed(evt);
            }
        });

        lblTglPemesanan1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTglPemesanan1.setText("Tanggal Pengiriman");

        txtTglPengiriman.setDateFormatString("dd MMMM yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNoSuratBaru)
                            .addComponent(lblPengirim))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoSuratJalanBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCariPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTglPemesanan)
                            .addComponent(lblCustomer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCariCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTglPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTglPemesanan1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel))
                            .addComponent(txtTglPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoSuratBaru)
                    .addComponent(txtNoSuratJalanBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPengirim)
                    .addComponent(txtPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariPengirim))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCustomer)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCariCustomer)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTglPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTglPemesanan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTglPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTglPemesanan1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnCancel))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(this, 
            "Apakah anda yakin ingin menutup form?", "Tutup Form", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            this.setVisible(false);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnCariPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPengirimActionPerformed
        this.setVisible(false);
        new CariPengirimForm(entity).setVisible(true);
    }//GEN-LAST:event_btnCariPengirimActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        boolean result = false;
        int idSuratJalan = 0;
        String noSuratJalan = txtNoSuratJalanBaru.getText();
        try{
            entity.setNoSuratJalan(noSuratJalan);
            entity.setTanggalPemesanan(((JTextField)txtTglPemesanan.getDateEditor().getUiComponent()).getText());
            entity.setTanggalPengiriman(((JTextField)txtTglPengiriman.getDateEditor().getUiComponent()).getText());
            result = dao.createSuratJalan(entity);
            if(result){
                entity.setIdSuratJalan(dao.getIdSuratJalan(noSuratJalan));
                this.setVisible(false);
                new DetailSuratJalanForm(entity).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Error Membuat Surat Jalan Baru!");
            }
        }catch(Exception e){
            try {
                throw new Exception(e);
            } catch (Exception ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
        new SuratJalanForm(entity).setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerActionPerformed

    private void btnCariCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariCustomerActionPerformed
        this.setVisible(false);
        new CariCustomerForm(entity).setVisible(true);
    }//GEN-LAST:event_btnCariCustomerActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCariCustomer;
    private javax.swing.JButton btnCariPengirim;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblNoSuratBaru;
    private javax.swing.JLabel lblPengirim;
    private javax.swing.JLabel lblTglPemesanan;
    private javax.swing.JLabel lblTglPemesanan1;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtNoSuratJalanBaru;
    public javax.swing.JTextField txtPengirim;
    private com.toedter.calendar.JDateChooser txtTglPemesanan;
    private com.toedter.calendar.JDateChooser txtTglPengiriman;
    // End of variables declaration//GEN-END:variables
}
